apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr
  namespace: arr
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /storage/kubernetes
    server: 10.0.0.31
  persistentVolumeReclaimPolicy: Delete
