apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: arr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 200Mi 
      
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 9696
        env:
        - name: PGID
          value: "666"
        - name: PUID
          value: "1002"
        - name: TZ
          value: "America/Los_Angeles" 
        volumeMounts:
        - name: prowlarr-config
          mountPath: /config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arr
  labels:
    app: prowlarr
    kubernetes.io/name: "prowlarr"
spec:
  selector:
    app: prowlarr
  ports:
  - name: prowlarr
    port: 80
    targetPort: 9696

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: arr
spec:
  ingressClassName: nginx
  rules:
  - host: prowlarr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80
  - host: prowlarr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80