---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
stringData:
  userID: kubernetes-cephfs
  userKey: key = AQAy2V5jYP4vFxAAQ9EBKE4Sn5U7lkJa3GxuXw==
  adminID: admin
  adminKey: AQDNE15jKR1CABAA44BA7GRu/kNOYD7tT8ikPg==