apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: arr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 20Mi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        imagePullPolicy: Always
        ports:
        - containerPort: 6789
        env:
        - name: PGID
          value: "666"
        - name: PUID
          value: "1002"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: nzbget-config
          mountPath: /config
        - name: nzbget-download
          mountPath: /download
      volumes:
        - name: nzbget-config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: nzbget-download
          hostPath:
            path: /storage/Uploads/Usenet

---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: arr
  labels:
    app: nzbget
    kubernetes.io/name: "nzbget"
spec:
  selector:
    app: nzbget
  ports:
  - name: nzbget
    port: 80
    targetPort: 6789

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
  namespace: arr
spec:
  ingressClassName: nginx
  rules:
  - host: nzbget.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget
            port:
              number: 80
  - host: nzbget
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget
            port:
              number: 80